In [1]:
import numpy as np 
import pandas as pd 
data = pd.read_csv("/home/jampanasasank/Desktop/Customer Churn Prediction/Telecom Churn Prediction/archive (7)/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [2]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
data.shape

(7043, 21)

In [5]:
data.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [6]:
data['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [7]:
data.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

No null values

In [8]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [9]:
data.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [10]:
cat_cols = ['gender', 'Partner', 'Dependents','PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod']

In [11]:
data[cat_cols]

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
0,Female,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check
1,Male,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check
2,Male,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check
3,Male,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic)
4,Female,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,Yes,Yes,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check
7039,Female,Yes,Yes,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic)
7040,Female,Yes,Yes,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check
7041,Male,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check
7042,Male,No,No,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic)

In [12]:
for i in cat_cols:
    print(data[i].value_counts(), '\n')

gender
Male      3555
Female    3488
Name: count, dtype: int64

Partner
No     3641
Yes    3402
Name: count, dtype: int64

Dependents
No     4933
Yes    2110
Name: count, dtype: int64

PhoneService
Yes    6361
No      682
Name: count, dtype: int64

MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X = data.drop(['Churn'], axis=1)
Y = data[['Churn']]

In [15]:
X_train, X_test , Y_train, Y_test = train_test_split(X, Y, random_state=42, test_size=0.2)

In [16]:
X_train.shape, X_test.shape

((5634, 20), (1409, 20))

In [17]:
from sklearn.preprocessing import LabelEncoder

# Initialize an empty list to store the encoders for each feature
label_encoders = []

# Loop through each categorical column and apply LabelEncoder
for col in cat_cols:
    label_encoder = LabelEncoder()
    X_train[col] = label_encoder.fit_transform(X_train[col])
    X_test[col] = label_encoder.transform(X_test[col])

    # Create a new dictionary for each feature's encoder
    label_encoders_dict = {"feature": col, "encoder": label_encoder}
    label_encoders.append(label_encoders_dict)  # Append to list

# Now label_encoders will have a dictionary for each feature with its encoder
print(label_encoders)

[{'feature': 'gender', 'encoder': LabelEncoder()}, {'feature': 'Partner', 'encoder': LabelEncoder()}, {'feature': 'Dependents', 'encoder': LabelEncoder()}, {'feature': 'PhoneService', 'encoder': LabelEncoder()}, {'feature': 'MultipleLines', 'encoder': LabelEncoder()}, {'feature': 'InternetService', 'encoder': LabelEncoder()}, {'feature': 'OnlineSecurity', 'encoder': LabelEncoder()}, {'feature': 'OnlineBackup', 'encoder': LabelEncoder()}, {'feature': 'DeviceProtection', 'encoder': LabelEncoder()}, {'feature': 'TechSupport', 'encoder': LabelEncoder()}, {'feature': 'StreamingTV', 'encoder': LabelEncoder()}, {'feature': 'StreamingMovies', 'encoder': LabelEncoder()}, {'feature': 'Contract', 'encoder': LabelEncoder()}, {'feature': 'PaperlessBilling', 'encoder': LabelEncoder()}, {'feature': 'PaymentMethod', 'encoder': LabelEncoder()}]

In [18]:
label_encoders

[{'feature': 'gender', 'encoder': LabelEncoder()},
 {'feature': 'Partner', 'encoder': LabelEncoder()},
 {'feature': 'Dependents', 'encoder': LabelEncoder()},
 {'feature': 'PhoneService', 'encoder': LabelEncoder()},
 {'feature': 'MultipleLines', 'encoder': LabelEncoder()},
 {'feature': 'InternetService', 'encoder': LabelEncoder()},
 {'feature': 'OnlineSecurity', 'encoder': LabelEncoder()},
 {'feature': 'OnlineBackup', 'encoder': LabelEncoder()},
 {'feature': 'DeviceProtection', 'encoder': LabelEncoder()},
 {'feature': 'TechSupport', 'encoder': LabelEncoder()},
 {'feature': 'StreamingTV', 'encoder': LabelEncoder()},
 {'feature': 'StreamingMovies', 'encoder': LabelEncoder()},
 {'feature': 'Contract', 'encoder': LabelEncoder()},
 {'feature': 'PaperlessBilling', 'encoder': LabelEncoder()},
 {'feature': 'PaymentMethod', 'encoder': LabelEncoder()}]

In [19]:
X_train.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
2142,4223-BKEOR,0,0,0,1,21,1,0,0,2,0,2,0,0,2,1,0,3,64.85,1336.8
1623,6035-RIIOM,0,0,0,0,54,1,2,1,0,2,0,0,2,2,2,1,0,97.20,5129.45
6074,3797-VTIDR,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,2,23.45,23.45
1362,2568-BRGYX,1,0,0,0,4,1,0,1,0,0,0,0,0,0,0,1,2,70.20,237.95
6754,2775-SEFEE,1,0,0,1,0,1,2,0,2,2,0,2,0,0,2,1,0,61.90,

In [20]:
X_test.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
185,1024-GUALD,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,2,24.80,24.8
2715,0484-JPBRU,1,0,0,0,41,1,2,2,1,1,1,1,1,1,0,1,0,25.25,996.45
3825,3620-EHIMZ,0,0,1,1,52,1,0,2,1,1,1,1,1,1,2,0,3,19.35,1031.7
1807,6910-HADCM,0,0,0,0,1,1,0,1,0,0,2,0,0,0,0,0,2,76.35,76.35
132,8587-XYZSF,1,0,0,0,67,1,0,0,0,0,0,2,0,0,2,0,0,50.55,3260.1

In [21]:
X_train.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [22]:
from sklearn.preprocessing import MinMaxScaler

num_cols = ['tenure','MonthlyCharges', 'TotalCharges' ]
X_train[num_cols]

      tenure  MonthlyCharges TotalCharges
2142      21           64.85       1336.8
1623      54           97.20      5129.45
6074       1           23.45        23.45
1362       4           70.20       237.95
6754       0           61.90
...      ...             ...          ...
3772       1           95.00           95
5191      23           91.10       2198.3
5226      12           21.15       306.05
5390      12           99.45      1200.15
860       26           19.80        457.3

[5634 rows x 3 columns]

In [23]:
X_train[num_cols].iloc[0]

tenure                21
MonthlyCharges     64.85
TotalCharges      1336.8
Name: 2142, dtype: object

In [24]:
X_train['TotalCharges'] = pd.to_numeric(X_train['TotalCharges'], errors='coerce')
X_test['TotalCharges'] = pd.to_numeric(X_test['TotalCharges'], errors='coerce')

In [25]:
from sklearn.preprocessing import MinMaxScaler
scalers = {}
for col in num_cols:
    scaler = MinMaxScaler()
    X_train[col] = scaler.fit_transform(X_train[[col]])
    X_test[col] = scaler.transform(X_test[[col]])
    scalers[col] = scaler
print(scalers)

{'tenure': MinMaxScaler(), 'MonthlyCharges': MinMaxScaler(), 'TotalCharges': MinMaxScaler()}

In [26]:
X_train

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
2142,4223-BKEOR,0,0,0,1,0.291667,1,0,0,2,0,2,0,0,2,1,0,3,0.464375,0.152089
1623,6035-RIIOM,0,0,0,0,0.750000,1,2,1,0,2,0,0,2,2,2,1,0,0.786746,0.589736
6074,3797-VTIDR,1,0,1,0,0.013889,0,1,0,0,0,0,0,0,0,0,1,2,0.051819,0.000537
1362,2568-BRGYX,1,0,0,0,0.055556,1,0,1,0,0,0,0,0,0,0,1,2,0.517688,0.025288
6754,2775-SEFEE,1,0,0,1,0.000000,1,2,0,2,2,0,2,0,0,2,1,0,0.434978,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,0684-AOSIH,1,0,1,0,0.013889,1,0,1,2,0,0,0,2,2,0,1,2,0.764823,0.008793
5191,5982-PSMKW,0,0,1,1,0.319444,1,2,0,2,2,2,2,2,2,2,1,1,0.725959,0.251500
5226,8044-BGWPI,1,0,1,1,0.166667,1,0,2,1,1,1,1,1,1,0,1,2,0.028899,0.033147
5390,7450-NWRTR,1,1,0,0,0.166667,1,2,1,0,0,2,0,2,2,0,1,2,0.809168,0.136320
860,4795-UXVCJ,1,0,0,0,0.361111,1,0,2,1,1,1,1,1,1,1,0,1,0.015446,0.050600

In [27]:
X_test

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
185,1024-GUALD,0,0,1,0,0.013889,0,1,0,0,0,0,0,0,0,0,1,2,0.065272,0.000692
2715,0484-JPBRU,1,0,0,0,0.569444,1,2,2,1,1,1,1,1,1,0,1,0,0.069756,0.112814
3825,3620-EHIMZ,0,0,1,1,0.722222,1,0,2,1,1,1,1,1,1,2,0,3,0.010962,0.116882
1807,6910-HADCM,0,0,0,0,0.013889,1,0,1,0,0,2,0,0,0,0,0,2,0.578974,0.006641
132,8587-XYZSF,1,0,0,0,0.930556,1,0,0,0,0,0,2,0,0,2,0,0,0.321873,0.374025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6366,2845-KDHVX,0,0,1,0,0.888889,1,0,0,0,2,2,2,0,2,2,1,3,0.498754,0.503116
315,5027-YOCXN,1,0,1,1,0.708333,1,2,1,2,2,0,2,2,2,1,0,1,0.914798,0.654004
2439,8884-MRNSU,1,0,1,1,0.236111,1,0,2,1,1,1,1,1,1,1,0,0,0.016442,0.035882
5002,0567-XRHCU,0,0,1,1,0.958333,0,1,0,2,0,2,0,0,2,2,1,1,0.256104,0.339407
1161,5868-CZJDR,1,0,0,1,0.013889,0,1,0,0,2,0,0,0,0,0,1,3,0.130543,0.001448

In [28]:
label_encoders

[{'feature': 'gender', 'encoder': LabelEncoder()},
 {'feature': 'Partner', 'encoder': LabelEncoder()},
 {'feature': 'Dependents', 'encoder': LabelEncoder()},
 {'feature': 'PhoneService', 'encoder': LabelEncoder()},
 {'feature': 'MultipleLines', 'encoder': LabelEncoder()},
 {'feature': 'InternetService', 'encoder': LabelEncoder()},
 {'feature': 'OnlineSecurity', 'encoder': LabelEncoder()},
 {'feature': 'OnlineBackup', 'encoder': LabelEncoder()},
 {'feature': 'DeviceProtection', 'encoder': LabelEncoder()},
 {'feature': 'TechSupport', 'encoder': LabelEncoder()},
 {'feature': 'StreamingTV', 'encoder': LabelEncoder()},
 {'feature': 'StreamingMovies', 'encoder': LabelEncoder()},
 {'feature': 'Contract', 'encoder': LabelEncoder()},
 {'feature': 'PaperlessBilling', 'encoder': LabelEncoder()},
 {'feature': 'PaymentMethod', 'encoder': LabelEncoder()}]

In [29]:
X_train.drop(['customerID'], axis=1, inplace=True)
X_test.drop(['customerID'], axis=1, inplace=True)

In [30]:
Y_train['Churn'].replace({'Yes':1, 'No': 0}, inplace=True)

/tmp/ipykernel_299499/681312183.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Y_train['Churn'].replace({'Yes':1, 'No': 0}, inplace=True)
/tmp/ipykernel_299499/681312183.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Y_train['Churn'].replace({'Yes':1, 'No': 0}, inplace=True)

In [31]:
Y_train

      Churn
2142      0
1623      0
6074      1
1362      1
6754      0
...     ...
3772      1
5191      0
5226      0
5390      1
860       0

[5634 rows x 1 columns]

In [32]:
Y_test

     Churn
185    Yes
2715    No
3825    No
1807   Yes
132     No
...    ...
6366    No
315     No
2439    No
5002    No
1161   Yes

[1409 rows x 1 columns]

In [33]:
Y_test['Churn'].replace({'Yes':1, 'No': 0}, inplace=True)

/tmp/ipykernel_299499/3467780579.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Y_test['Churn'].replace({'Yes':1, 'No': 0}, inplace=True)
/tmp/ipykernel_299499/3467780579.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Y_test['Churn'].replace({'Yes':1, 'No': 0}, inplace=True)

In [34]:
import xgboost as xgb

In [35]:
model = xgb.XGBClassifier()
model.fit(X_train, Y_train)
preds = model.predict(X_test)

In [36]:
preds

array([1, 0, 0, ..., 0, 0, 1])

In [37]:
Y_test.value_counts()

Churn
0        1036
1         373
Name: count, dtype: int64

In [38]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, preds, target_names=['No', 'Yes'], digits=4))

              precision    recall  f1-score   support

          No     0.8344    0.8948    0.8635      1036
         Yes     0.6342    0.5067    0.5633       373

    accuracy                         0.7921      1409
   macro avg     0.7343    0.7007    0.7134      1409
weighted avg     0.7814    0.7921    0.7841      1409

In [39]:
model

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [40]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
import pickle as pkl

class DataPrep:
    def __init__(self, data, artifacts_path) -> None:
        self.data = data
        self.artifacts_path = artifacts_path
        print(self.artifacts_path)
        X = self.data.drop(['Churn'], axis=1)
        Y = self.data[['Churn']]
        self.X_train, self.X_test, self.Y_train, self.Y_test = train_test_split(X, Y, random_state=42, test_size=0.2)
    
    def save_artifacts(self, feature, encoder):
        path = f'{self.artifacts_path}/{feature}_estimator.pkl'
        with open(file=path, mode='wb') as f: 
            pkl.dump(encoder, f)
            
    def label_encode(self):
        cat_cols = [
            'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService',
            'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
            'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
            'PaymentMethod'
        ]
        
        for col in cat_cols:
            label_encoder = LabelEncoder()
            self.X_train[col] = label_encoder.fit_transform(self.X_train[col].copy())
            self.X_test[col] = label_encoder.transform(self.X_test[col].copy())
            feature = f'{col}_label_encoder'
            self.save_artifacts(feature, label_encoder)
            
    def scaling(self):
        self.X_train['TotalCharges'] = pd.to_numeric(self.X_train['TotalCharges'], errors='coerce')
        self.X_test['TotalCharges'] = pd.to_numeric(self.X_test['TotalCharges'], errors='coerce')
        
        num_cols = ['tenure','MonthlyCharges', 'TotalCharges' ]

        
        for col in num_cols:
            scaler = MinMaxScaler()
            self.X_train[col] = scaler.fit_transform(self.X_train[[col]])
            self.X_test[col] = scaler.transform(self.X_test[[col]])
            feature = f'{col}_scaler'
            self.save_artifacts(feature, scaler)
        
    def drop_columns(self,):
        self.X_train.drop(['customerID'], axis=1, inplace=True)
        self.X_test.drop(['customerID'], axis=1, inplace=True)
        
    
    def target_replace(self, ):
        self.Y_train['Churn'].replace({'Yes':1, 'No': 0}, inplace=True)
        self.Y_test['Churn'].replace({'Yes':1, 'No': 0}, inplace=True)
        
            
    def process(self):
        self.label_encode()
        self.scaling()
        self.drop_columns()
        self.target_replace()
        return self.X_train, self.X_test, self.Y_train, self.Y_test

In [41]:
artifacts_path = '/home/jampanasasank/Documents/Deployment/Deployment/telecom_churn_prediction/model'
data = pd.read_csv("/home/jampanasasank/Documents/Deployment/Deployment/telecom_churn_prediction/archive (7)/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [42]:
obj = DataPrep(data=data, artifacts_path=artifacts_path)

/home/jampanasasank/Documents/Deployment/Deployment/telecom_churn_prediction/model

In [43]:
X_train, X_test , Y_train, Y_test = obj.process()

/tmp/ipykernel_299499/1095122835.py:54: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.Y_train['Churn'].replace({'Yes':1, 'No': 0}, inplace=True)
/tmp/ipykernel_299499/1095122835.py:54: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.Y_train['Churn'].replace({'Yes':1, 'No': 0}, inplace=True)
/tmp/ipykernel_299499/1095122835.py:55: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.Y_test['Churn'].replace({'Yes':1, 'No': 0}, inplace=True)
/tmp/ipykernel_299499/1095122835.py:55: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.Y_test['Churn'].replace({'Yes':1, 'No': 0}, inplace=True)

In [44]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
import pickle as pkl

class ModelBuilding:
    def __init__(self, X_train, X_test, Y_train, Y_test, path):
        self.X_train = X_train
        self.X_test = X_test
        self.Y_train = Y_train
        self.Y_test = Y_test
        self.path = path
        self.model = None  # Initialize model attribute

    def build_model(self):
        self.model = xgb.XGBClassifier()  # Create the model
        self.model.fit(self.X_train, self.Y_train)  # Train the model
        self.save_artifacts()  # Save the model
    
    def evaluate_model(self):
        # Check if the model is trained
        if self.model is None:
            print("Model is not trained yet!")
            return
        
        # Make predictions
        predictions = self.model.predict(self.X_test)
        
        # Evaluate performance
        print("Accuracy score: ", accuracy_score(self.Y_test, predictions), '\n')
        print("Classification report: \n", classification_report(self.Y_test, predictions), '\n')
        print("Confusion Matrix: \n", confusion_matrix(self.Y_test, predictions), '\n')
        print("ROC AUC Score: ", roc_auc_score(self.Y_test, predictions), '\n')
    
    def save_artifacts(self):
        if self.model is None:
            print("No model to save!")
            return
        
        # Save the model using pickle
        path = f'{self.path}/model.pkl'
        with open(file=path, mode='wb') as f: 
            pkl.dump(self.model, f)
        print(f"Model saved to {path}")
    
    def build(self):
        self.build_model()  # Build the model
        self.evaluate_model()  # Evaluate the model

In [45]:
path = '/home/jampanasasank/Documents/Deployment/Deployment/telecom_churn_prediction/model'

In [46]:
obj1 = ModelBuilding(X_train, X_test , Y_train, Y_test, path=path)

In [47]:
obj1.build()

Model saved to /home/jampanasasank/Documents/Deployment/Deployment/telecom_churn_prediction/model/model.pkl
Accuracy score:  0.7920511000709723

Classification report:
               precision    recall  f1-score   support

           0       0.83      0.89      0.86      1036
           1       0.63      0.51      0.56       373

    accuracy                           0.79      1409
   macro avg       0.73      0.70      0.71      1409
weighted avg       0.78      0.79      0.78      1409


Confusion Matrix:
 [[927 109]
 [184 189]]

ROC AUC Score:  0.7007450288281388